### ISSUE TITLE
day to day NS report is not showing all data

### ISSUE THREAD

**Issue by thomasmenges** [nightscout/cgm-remote-monitor#4053]
**Describe the bug**
The day to day NS report has some problems. 
After using Glimp instead of XDRIP (I had to change because of connecting problems to my CGM system libre (miaomiao) the day to day report shows no BG data any more. But these values are shown correctly in the NS overview page. 

So, the values must be stored in mongo db. 

If you are using the new function of NS reporting (http://www.nightscout-reporter.zreptil.de/) all values are shown correctly. That means that the values are stored in MongoDB (NS) correctly but the day to day report have some problems showing the values.

What can be done to solve these problems ?

**Screenshots**
![image](https://user-images.githubusercontent.com/37514390/48305601-092cfe00-e52e-11e8-8c74-9b927c88f75b.png)

![image](https://user-images.githubusercontent.com/37514390/48305635-b9026b80-e52e-11e8-9512-ab756802cbd0.png)

**Your setup information**
I'm using NS 0.11.0-dev  on   ns.10be.de
I'm using libre (miomio --> glimp) and AAPS
The problem still exists in every browser!!!!!

**Comment by zehnBE** [comment]
can you look with browser "elemte untersuchen" (control + O  or Chrome control + shift + I) and look into the "network"-Tab and on "response", which the message/errors was?

**Comment by sulkaharo** [comment]
This is likely already fixed in the develop branch - are you running the release or dev version? If release, can you test using develop to see if that works?

**Comment by thomasmenges** [comment]
I'm using the dev branch as mentioned before.
After switching to the dev branch the problems with profile switches seem to be solved but the values from GLIMP are still missing.
So, I made some checks and I found some interesting things:

1) The missing values only occur when I'm using Glimp with connection to miaomiao. The values are delivered to NS and can be seen directliy in the NS overview (screenshot 1) but the values aren't shown in the day to day report. All other reports don't have these problems.
2) When I'm using Glimp are take the BG value with NFC instead using miaomiao the value is stored in NS and can be seen in the day to day report. Especially on Nov 12th you can see some BG values (taken with NFC ) (between 01.00 and 06.00 a.m) and the other ones later come from miaomiao --> no data is shown in the report (see the new screenshots below).

conclusion:
Yes, there seems to be some differences between Glimp (with and without miaomiao) but where must be  nevertheless a problem in the day to day report !!!!!!
Other webpages can fetch all the NS data and bring them on a graphic (http://www.nightscout-reporter.zreptil.de/).

I also had a look with browser (like Martin wrote) "elemte untersuchen" (control + O or Chrome control + shift + I) and look into the "network"-Tab and on "response", which the message/errors was?  ---> but there were no errors mentioned.

Screenshot 1 (Overview 12. nov. 2018)
![image](https://user-images.githubusercontent.com/37514390/48426306-d15ccb00-e766-11e8-8fc3-18f22a91af38.png)

screenshot 2 (day to day report --> missing data)
![image](https://user-images.githubusercontent.com/37514390/48426414-079a4a80-e767-11e8-97a6-8e11fbd224fe.png)

screenshot 3 (http://www.nightscout-reporter.zreptil.de/)
![image](https://user-images.githubusercontent.com/37514390/48426450-1d0f7480-e767-11e8-8add-c573dea5ce39.png)

**Comment by sulkaharo** [comment]
This sounds like a bug in the data Glimp is sending to Nightscout, not a Nightscout bug. Can you send a sample of what the Glimp SGV records look like so we can check what the issue is?

**Comment by thomasmenges** [comment]
@PieterGit I have attached the MongoDB Backup. I hope that there are information inside you can use.
[2018-11-13_00.tar.gz](https://github.com/nightscout/cgm-remote-monitor/files/2589161/2018-11-13_00.tar.gz)

**Comment by moskolowosky** [comment]
I have the same problem . I hope they resolve ASAP

**Comment by sulkaharo** [comment]
@thomasmenges thank you for the dump. Looks like Glimp data has several issues:

1) date field content is misformatted. Nightscout expects an integer, glimp seems to output a floating point number
2) sgv delta field is missing
3) noise classification field is missing

@PieterGit wonder if we should add data checking for ^^? The delta field could maybe be optional but I think we will want the date field to be correctly formatted and the noise data not coming in is really bad, especially if someone uses the data for looping.
