### ISSUE TITLE
No new reading in Nightscout for over 15 hours

### ISSUE THREAD

**Issue by tracey3290** [nightscout/cgm-remote-monitor#5608]
Hi
Having issues with night scout since just before midnight yesterday now over 15 hours without readings to Nightscout.  Have reset dynos but now luck

**Comment by parapenT1sta** [comment]
https://loopkit.github.io/loopdocs/nightscout/mlab_cleanup/

**Comment by tracey3290** [comment]
Thanks tried all that still not worked. 

Tracey

**Comment by ideaweb** [comment]
I have the same issue since last night. Could it be that Dexcom API is offline? I played a bit with curl and was not able to retrieve a session ID always 0000... But maybe I made a mistake with curl. Anyway I guess something with Dexcom API is wrong.

**Comment by tracey3290** [comment]
Thanks Tom

**Comment by iqhu** [comment]
I have the same problem, interestingly enough on both my heroku nightscout website and xdrip+ (which uses dexcom share data as source). The last reading on nightscout I got was approx. 1am CET on April 9th, while on xdrip, the last reading was 8.30am the same day.

Before I try the tutorial above and delete all my data, is there a way to back up the data? I don't want to loose by BG and treatments...

While both xdrip and nightscout cannot read the share output anymore, the dexcom follow up still receives readings. BTW, I am based in Europe, if that makes a difference.

**Comment by Josef-A** [comment]
We have the same problem. No data since April 9th 00:47 (Stockholm time). The problems seems to be the connection with Dexcom share. Neither NS or xDrip can get data. But Dexcom Follow works.
Several users in Sweden have the same issue. But there are also users with no problem at all. xDrip worked a few hours more (6 am). I guess that xDrip hold on to the same login session until that.

Let me know if I should send any log files or test anything.

**Comment by iqhu** [comment]
I didn't get it fixed, so I am now using xdrip to collect the Decom data, which is then uploaded to my Nightscout site. Unfortunately, this way my doc cannot track my BG levels anymore. But day-to-day ease of use is more important to me. Happy to hear if someone get the Dexcom Share issue properly fixed, though.

**Comment by ideaweb** [comment]
Unfortunately XDrip for collecting is not an option for us, always Bluetooth connection issues to the Transmitter after some time with our Jelly Pro. I don’t like the Dexcom App but I can trust that it works which is very important for our little kid. I hope someone can find the troublemaker or find a workaround. Is there any specialist around having an idea? E.g. is there any app for Android which could grab the value from Dexcom App on lock screen and send it via HTTP?

**Comment by Josef-A** [comment]
We are in the same situation as @ideaweb. I heard about a patched Dexcom app. It might be able to get data to both Dexcom share and NS. But I am reluctant to switch from Dexcoms own app as long as that part works.

I have made some tests.
If I understand it corrects the API for Dexcom share is documented in nightscout/share2nightscout-bridge#15
With my account I am able to retrieve a session id with _AuthenticatePublisherAccount_, but when I try with _LoginPublisherAccountByName_ I get an session id of '00000000-0000-0000-0000-000000000000'.

If I then try to get some values with _ReadPublisherLatestGlucoseValues_ by using the session id I got earlier I get a error message: SessionIdNotFound.

Does anyone have more information on how this API works.
Why are there, for example, two methods for getting a session id?
What I can see from the code Nightscout only uses _LoginPublisherAccountByName_.

Is there anyone who has time to help, or at least can explain a little more.
Do you @bewest have any comments?

As it is now, I've been stuck. I do not have enough knowledge to troubleshoot Nightscout.

**Comment by ideaweb** [comment]
Question is really, did Dexcom made a mistake and broke its own API, in hope that it’s fixed soon, or they blocked „us“ because of to many API requests? Any chance to check the API with another applicationId? How I can get a new one for a test?

**Comment by jmphillips33** [comment]
Our dexcom data stopped being displayed in NS on 4/8. It was suggested on a post in the fb group to delete and re-enter the bridge user name and password in Heroku. I did that and also restarted the dynos and our dexcom data is now being displayed in NS again. Seems some are having luck with trying this but not everyone. Hope it helps someone.

**Comment by HollimGMG6** [comment]
Same issue here since last Thursday, tried the restart/re-enter details fix, redeployed and even set up a brand new heroku and NS but its still not working. I also wondered if Dexcom were blocking us due to hitting the request call limit but it's 60k per hour from what I've read. This is really starting to annoy me now as I'm out of ideas, I have fired a support request to the Dexcom developer portal but so far nothing back.

**Comment by HollimGMG6** [comment]
So the response back from the Dexcom developer support was no help as expected (worth a try). Has anyone managed to get this working beyond creating a whole new dexcom account from scratch ?

**Comment by ideaweb** [comment]
I created a new (unverified) account outside the US and its still not not working, but with a new (unverified) US account it works!

Could a be that by "law" Dexcom cannot offer an API outside of the US? I did not know until now that here it uses an unofficial API. Is it legal to use it?

The official API at https://developer.dexcom.com/ is only for the US. They have the technique but in FAQs they excused with "Working on it" (https://developer.dexcom.com/content/frequently-asked-questions). 

But of course like other companies they closed the "leak" in the unofficial API because of marketing reasons... who knows.

**Comment by HollimGMG6** [comment]
I hope not, I know some in the EU region have had their's start working  through randomly re-entering bridge details or redeploying NS, seems to be pot luck more than anything

**Comment by jmphillips33** [comment]
We are in the US and re-entering the credentials into Heroku worked for us. I deleted the entries, saved, then re-entered and saved, then restarted the dynos. Fingers crossed it keeps working.

**Comment by sigbjorn88** [comment]
Same problem here, Norway/EU. 
Reinstalled app, deleted and inserted bridge usn/pwd, restarted dynos, cleared databases (which only contained 1mb anyway), redeployed app with US as location. All these in separate steps.
Nothing worked. App is set up but no data imported. 
Reluctant to set up a new Dexcom account as mine is also linked to my doctor and hospital.

**Comment by HollieMiaoMiao** [comment]
@sigbjorn88  done exactly as you have even set a new NS up from scratch and nothing worked, the current Dexcom account is also linked to to the care team. Out of ideas now, really frustrating

**Comment by Robin-H88** [comment]
Hello,
I come from Germany and I have the same problem as described.

Is this website already known?
https://developer.dexcom.com/

**Comment by Josef-A** [comment]
Thats Dexcoms official API. That's well documented but have the limitation that data is lagging three hours. Nightscout uses Dexcom share API. Sort of documented in  nightscout/share2nightscout-bridge#15

**Comment by Josef-A** [comment]
I have made a little Python script to workaround the problem.
See https://github.com/Josef-A/sugarmate2nightscout

It uses the fact that follower still works. The problem with follower is that you need to implement all handling of follower. I don't know how to implement that. But Sugarmate have solved that, and they have a simple JSON API to get glucose value. My script just take readings from Sugarmate and load them to Nightscout. This solution has some drawbacks

* You only have the latest glucose reading. That means that there is no way to back fill gaps of data.
* My script does not check if the glucose reading already exists in Nightscout. (Can be fixed, when I got time)
* It will take up one follower in Dexcom

Just a little warning. I made this script as a quick workaround, It does not have proper error handling yet. I do not have that much experience with deployment. But it will probably run if you check it out from GitHub. I also put up an exe-file for those not familiar with Python.

**Comment by Josef-A** [comment]
Just to summarize some thoughts

The problem seems to be that Dexcom have made some changes that affect some users. Dexcoms share API have methods directed to the sender app and other methods for the follow app.
Nightscout uses the methods directed to the sender app. 
But if Nightscout could use the methods for the follow app it would probably work also for us that have these problem now.

I think the best solution would be to implement both methods in [share2nightscout-bridge](https://github.com/nightscout/share2nightscout-bridge). The user could then choose which method to fill in credential for. It’s even possible to use both, one as a primary method and the other as a fallback.

What needs to be implemented is some routines that handle the invitation and credential handling for the follower.

I have seen some discussion about to have Nightscout as a follower to Dexcom in Gitter. The problem seems to be the lack of documentation of the share API.

Inspired by [scott]( https://www.hanselman.com/blog/BridgingDexcomShareCGMReceiversAndNightscout.aspx) I tried to parse the packets send to/from both the sender app and the follow app. But I could not get pass the SSL-encryption. But I have never done that before so I might do it wrong.
Do you have any tips here @shanselman.

Another approach is just to ask Sugarmate how they solved this. They might be willing to tell us. Does anyone have contact with them?

Do you who have thought about this earlier have any comments?
@scottleibrand, @bewest

**Comment by scottleibrand** [comment]
I'm likely not going to be able to get to this for a few weeks or months (depending on how long it takes us to get COVID-19 under control and the economy reopened) unless it starts affecting us personally.

**Comment by sulkaharo** [comment]
Ok one thing that's maybe worth checking is, the Dexcom Share API appears now stricter than before regarding usernames and will fail if a username contains anything but alphanumeric characters. Anyone with Share issues might want to double check all usernames and passwords on their accounts contain only letters and numbers.

**Comment by Josef-A** [comment]
Good suggestion @sulkaharo. But I think that's already tested.
I do only have alpha-numerics in my password. I have tested to change both password and changed to a brand new account. 
I do have a period in my user name. But since they have routines for not accepting passwords that do not match their criteria, they should not allow usernames that they do not support.

But on the other hand, some users have got it started by changing their password or changing their account

**Comment by den-saunders** [comment]
> Good suggestion @sulkaharo. But I think that's already tested.
> I do only have alpha-numerics in my password. I have tested to change both password and changed to a brand new account.
> I do have a period in my user name. But since they have routines for not accepting passwords that do not match their criteria, they should not allow usernames that they do not support.
> 
> But on the other hand, some users have got it started by changing their password or changingmy user name had a “.” in it.

Actually I think @sulkaharo is on to something. I had removed the non-A# characters from my password a few days ago without success...However this is the first suggestion that the rules around this may also have tightened for username. Since mine had a “.”, I made a new profile with ONLY A# and bridge to nightscout is working again!

FYI, you can’t change your existing username - but you can change your email in your dexcom clarity account to a secondary email, to free up your primary for a new account without any special characters in username or password. This way all your existing dexcom data is retained in your original account should you need/want to look back at it.

**Comment by Josef-A** [comment]
Thanks @sulkaharo and @den-saunders.
I haven't tested it for full. But I have made a new account (my fourth). This time without period in it.
Now I am able to get a real session id from _LoginPublisherAccountByName_. Really promising.
But I have to wait until my son is back from school to make any real tests.

**Comment by sigbjorn88** [comment]
Let me know how it works!
I tried adding a "dependent profile" user on Dexcom with a new username with only letters and pwd with number and small and capital letters, no spaces or special signs. 
Did not work for me at least.

**Comment by HollimGMG6** [comment]
Yep tried the same with a dependent account no special characters in the name or password, still no good for me.

the main account is my email address so that has  @ in it so I cant change that, will try changing the password for it but I wonder if it's the main account that needs to be free of special characters.

**Comment by den-saunders** [comment]
> Yep tried the same with a dependent account no special characters in the name or password, still no good for me.
> 
> the main account is my email address so that has @ in it so I cant change that, will try changing the password for it but I wonder if it's the main account that needs to be free of special characters.

I would suggest trying an alternate “main account” without special characters. Again - to make sure you don’t lose your CGM data which you at least have accessible in clarity, don’t delete your current account - rather in the clarity settings reassign it to an alternate email address. The dexcom rules are one “main account” per email. Put you can have a couple if you have a couple emails. Then delete the dexcom app on your mobile, reinstall, sign in with new credentials, and put in your sensor and transmitter numbers - it will recover where is left off without any warm up, or issue. Make sure this new symbol-less user and password are updated in your Herokuapp config vars, and restart the synod for good measure.

**Comment by Josef-A** [comment]
Now have I tested. It works!
Thanks all!

Can some more test, just so we know it's for real and not just plain luck?

**Comment by HollimGMG6** [comment]
That is promising, I'll set up a new account shortly and let you know

**Comment by ideaweb** [comment]
I created a new account w/o a dot in the username... it works! Thx!

**Comment by Josef-A** [comment]
I wrote some instructions of how to change the Dexcom account.
https://github.com/Josef-A/sugarmate2nightscout/blob/master/how_to_fix_en.md
Maybe not the best place to put it, but it was easy for me.

Can someone read and comment if something is wrong/misleading or could be rephrased.

**Comment by sigbjorn88** [comment]
Worked here as well. Also contacted local support who also recommended changing email linked to account, creating a new account and use your "old" mail (if ypu deem that necessary) to get the new username without special signs.

**Comment by HollimGMG6** [comment]
@Josef-A  I followed your guide and we are back in business, great work and thanks to everyone else in the thread @den-saunders @sulkaharo  etc that have assisted.

Still find it frustrating Dexcom would just change that with out any kind of release\update notification but there you go.

**Comment by Josef-A** [comment]
My guess is that Dexcom didn't change this by purpose. Probably that some routine that handles user name have changed and it can not handle all character. If it were by purpose I would have expected an error code.

**Comment by Josef-A** [comment]
What I seen from comments on Facebook I think that this issue is resolved.

But before we close it I think it would be good to: 
* Document this on the installation guide for Nightscout. 

* Report back to Dexcom. It would be nice if Dexcom implement a routine to restrict the choice of user name when a user create a new account.

Can someone help me with this. I haven't setup a local dev version of Nightscout, and I do not have so much experience of pull requests, so it would take rather long time for me to fix that.

Does anyone have any contact with Dexcom? I do not know what they think about that Nightscout uses there Share API. If they really don't like it, it might be better to not report back.

**Comment by ryanchen26** [comment]
This might be the solution for some cases but not all. This doesn't solve those instances where a particular login works when I test it in California, but it doesn't work for the actual user in Texas or Florida for example.

**Comment by Josef-A** [comment]
> 
> 
> This might be the solution for some cases but not all. This doesn't solve those instances where a particular login works when I test it in California, but it doesn't work for the actual user in Texas or Florida for example.

Just so we know it's the same problem:
Works Dexcom Follow for these users?
If they call _LoginPublisherAccountByName_, do they get a session id like '00000000-0000-0000-0000-000000000000'?

**Comment by ryanchen26** [comment]
Correct, share works (follow app receiving data), and the use of that endpoint for them results in a session ID of all-zeros.  Few hours ago I took a look at the follow app traffic using Fiddler. I'm at the point of trying to decrypt the body of the initial post to understand what info needs to be sent to get the session id, and then to eventually get the bg data. I've seen evidence that this has already been done. This is one of those cases where I am not directly impacted but I'd like to settle this matter.

**Comment by Josef-A** [comment]
Would be great if you could document the endpoints from a followers view. Then we could have two methods to get BG.

* Did you get it to work with their credentials but not the users themselves?
* Do they have a user name with only character a-z?
* Have they setup a new account?

**Comment by ryanchen26** [comment]
Yes to the first question if they are in the US. Second, yeah I relayed that observation and I haven't seen any success stories in my group from those that tried...maybe it worked and they never confirmed. Third, I believe so, but hard to track. Some just get frustrated and give up. 

For Fiddler, I'm just poking around...had no luck with android, but I'm seeing stuff with iOS. I think I would need to do it again, but start over to see how the account ID is initialized. The app ID is the same one that has been floating around. The response from list subscribers is unfamilar to me. Hmac? But somehow out of that you get a session ID and then the ReadEvents endpoint spits out the latest BG value.  

So, that's what I can see after a couple hours. Not sure what to do next or if this is even worth pursuing. Thoughts?

**Comment by ryanchen26** [comment]
For what it's worth, it was determined that if there was a blank space in the dexcom login password (I'm talking fitbit Sentinel clockface settings because that3s my thing) then you can reproduce the all-zeros response when requesting the session ID. So as of Sentinel Pro v0.2.8 all blank space before and after the username and password are removed just in case.

**Comment by meinmalli** [comment]
two months later and nothing changed. It took me two weeks to find this thread after so many unsuccessful attempts to get my values back into Nightscout. I had a dot in my username, set up a new account using only letters and it simply works. Annoyed that I lost all my clarity data. I contacted the german Dexcom support with this issue of not being able to change the username and problems with the API. Will give an update when I get a reasonable response.

**Comment by th-muller** [comment]
Hi, 
I have the issue (as addressed by [Josef-A's post](https://github.com/Josef-A/sugarmate2nightscout/blob/master/how_to_fix_en.md)) i.e. not getting any data into my Nightscout.
The reason I concluded was that my Dexcom username included an underscore ("_").
So I followed the steps as Josef described. But unfortunately it did not resolve my issue.
In the instructions it says, that if it works CGM values should become visible in a couple of minutes.
Now I have waited for > ½hour.

- I have created a new Dexcom account.
- Re-installed the Dexcom app on my iPhone.
- Updated the sharing (to another phone, that has the follower app installed - and it is working)
- Updated the Heroku app with the new credentials (BRIDGE_USER_NAME and BRIDGE_PASSWORD) by "Reveal Config Vars".
- MMCONNECT_SERVER and BRIDGE_SERVER are set to EU, since I have a Swedish Dexcom account.

- Any suggestions that might be the reason?

I attache two logs as it looks now and ½h ago.

[th-muller-ns-logs-1596400990086-202008012CET2313.txt](https://github.com/nightscout/cgm-remote-monitor/files/5012988/th-muller-ns-logs-1596400990086-202008012CET2313.txt)
[th-muller-ns-logs-1596400990086-202008012CET2244.txt](https://github.com/nightscout/cgm-remote-monitor/files/5012989/th-muller-ns-logs-1596400990086-202008012CET2244.txt)

Thanks for your time and possible help :-)

Regards
Thomas Müller
Sweden

**Comment by psonnera** [comment]
@Josef-A with your authorization adding this to clarify https://nightscout.github.io/troubleshoot/troublehoot/#dexcom-data-not-showing to close https://github.com/nightscout/nightscout.github.io/issues/79 Thanks

**Comment by okeetris** [comment]
Hello, I wondered upon this today as i am having this issue with my current setup. upon checking the suggestions in here and calling Dexcom support it turns out that they now have removed all usernames and they set the username to the email address as standard. 
So there is no option to be able to pick a username that does not include characters that are not in A-Z as all email addresses use '@'.

**Comment by Josef-A** [comment]
@okeetris 
According to this issue in the bridge plugin repository, it is probably solved. I haven't tested it. But it might be enough to redeploy your Nightscout at Heroku. If that do not work I guess that someone needs to issue a new release of Nightscout to use the new version of bridge plugin.

See:
https://github.com/nightscout/share2nightscout-bridge/issues/39

**Comment by bewest** [comment]
Correct, please let me know if redeploying your Heroku site works or not.

**Comment by ReilerUA** [comment]
Redeploying Heroku site doesn’t help. I am struggling with this problem right now.

**Comment by bewest** [comment]
Thanks for the feedback.  To be clear, are you able to log into https://clarity.dexcom.com/ or https://clarity.dexcom.eu/ in order to view data from 3 hours ago?  It looks like fresh checkouts will pull `share2nightscout-bridge@0.2.4` instead of `0.2.5`, which contains the latest fix.  I have created a pull request to update and track this: https://github.com/nightscout/cgm-remote-monitor/pull/7123

**Comment by ReilerUA** [comment]
Yes, I am able to access clarity portal.

**Comment by jordan-rouse** [comment]
Hi everyone, after experiencien the same issues as described above I found a solution that worked for me. It turned out to be quite simple after many hours of trying passwords changes etc. 
 I discovered my github branch was out of date and my heroku deployment had somehow disconnected itself. I followed this guide to update the github branch and re-connect / re-deploy to Heroku, now it works fine.  I am in Sweden:

https://nightscout.github.io/update/update/
