### ISSUE TITLE
Rendering of terminated remote overrides from Loop

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/cgm-remote-monitor#5992]
[With NS 14.0.2,] temporary overrides are still rendered below the BG chart after it has been disabled. 

System: Loop (FreeAPS)
NS is hosted with Heroku using mLab (not migrated to Atlas)

The remote overrides and override cancel still works from Careportal

The BG target pill is updated correctly.

Deploying Dev 13.1.0 as of  Aug 22, 2020, the temporary override rendering is terminated at the correct time.

14.0.2:
![image](https://user-images.githubusercontent.com/63544115/93091897-00b02c00-f69f-11ea-9cc9-75163d29e5e4.png)

13.1.0 Override terminated at red line
![image](https://user-images.githubusercontent.com/63544115/93092667-05c1ab00-f6a0-11ea-8752-470c49b5a74a.png)

**Comment by bjornoleh** [comment]
Re-deploying 14.0.2 renders the override correctly.

At a similar occurrence yesterday, restarting all dynos in Heroku also solved the problem. This was after deleting the entry from the "treatments" collection in mLab, which in itself did not remove the rendering of the override.

Given these observations, it is quite likely the issue is be independent of recent developments in Nightscout.

**Comment by bjornoleh** [comment]
Ok, I have confirmed that restarting dynos in Heroku is fixing the temp override display problem. It is probably unrelated to the NS version.

![image](https://user-images.githubusercontent.com/63544115/93127190-bbefb980-f6cd-11ea-9f6a-1235795899e5.png)

I could suspect the mLab database size to be the culprit, but it seems to be well within the limits. Also, the profile collection has been purged recently. 

Any hints for how to solve his is welcome, as it ca easily be a cause of confusion when communicating with other caregivers at school.

![image](https://user-images.githubusercontent.com/63544115/93126988-67e4d500-f6cd-11ea-848e-01445542d1b8.png)

![image](https://user-images.githubusercontent.com/63544115/93127051-82b74980-f6cd-11ea-9e0a-3ca9ebe54d6e.png)

**Comment by sulkaharo** [comment]
Am I correct this is with Loop?

**Comment by bjornoleh** [comment]
@sulkaharo yes, as mentioned in the title  :-)

**Comment by bjornoleh** [comment]
Minor update: restarting dynos was required to correctly display terminated temp overrides from Loop also after the mLab repairDatabase.

**Comment by bjornoleh** [comment]
Possibly not-so-minor update: 

Deployed Dev 13.1.0 as of Aug 22, 2020 
Activated Temporary override from Careportal 
Terminated with "Temporary override cancel" from Careportal: --> The override was rendered correctly, without needing restart of dynos

**Comment by sulkaharo** [comment]
@bjornoleh I know the cause for this. Can you test the latest DEV, it should fix this for overrides that have been issued up to three hours earlier. The real fix will take longer to implement.

**Comment by bjornoleh** [comment]
@sulkaharo Thanks, it's good to know you have found the cause. I just tested with latest DEV, but unfortunately it doesn't seem to fix it for me. I did a ctrl-f5 reload in Win10-Chrome to be sure the new build was active, this usually does the trick.

To be specific, this is what I deployed (previous deploy was Dev 13.1.0 as of Aug 22): 

Compare diff from Heroku "Latest activity":
https://github.com/bjornoleh/cgm-remote-monitor/compare/ed402e91...c839dc3d

Terminated after 4 minutes, still displayed as 60 min:
![image](https://user-images.githubusercontent.com/63544115/93197387-d9fbff00-f74b-11ea-97e6-632e897214f2.png)

After restart all dynos:
![image](https://user-images.githubusercontent.com/63544115/93197498-00219f00-f74c-11ea-86be-46f7b84175e5.png)

**Comment by sulkaharo** [comment]
Ok new attempt - can you update to the latest dev again. :)

**Comment by bjornoleh** [comment]
It seems like that did the trick, I have tested it twice, so I'm pretty sure :-)  Thank you!

I suppose overrides that were running for more than three hours will still be rendered after termination?

**Comment by sulkaharo** [comment]
Great to hear! I bumped the treatment delta sync to four hours now; anything older than that will still exhibit the glitch until we have the "real" fix.

**Comment by sulkaharo** [comment]
#6056 should fix this for good - if you want to help test, you'll need to deploy branch cache_invalidation to your Heroku setup

**Comment by bjornoleh** [comment]
@sulkaharo 
I tested activating and terminating a remote override after deploying the cache_invalidation branch. This worked as expected, and the terminated override was rendered correctly.  This was just a short lasting one though, I have not tried anything else.

**Comment by bjornoleh** [comment]
Still working in the testing branch as of today, but only tested in the short term.

**Comment by bjornoleh** [comment]
Working also for long term overrides after this fix:

https://github.com/nightscout/cgm-remote-monitor/pull/6056
