### ISSUE TITLE
Cage warning?

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#710]
I have a cannula showing 165 hours (because I didn't careportal log the last change). Seeing that, I enabled the cannula warning variables to get a look at how the warnings work (where they appear, what they trigger, etc.). (I was thinking that in addition to any warning triggered, the cage text might appear red for a visual indicator in the pillbox if the age met one of the configured thresholds. I was also looking to see/test if the cage warning triggered ns-event)

But I am not seeing the variables take effect. Once we site change today, I will watch for the next aging cycle... but flagging issue in case there is something else going on.

/api/v1/json shows variables are set

{"status":"ok","apiEnabled":true,"careportalEnabled":true,"enabledOptions":"simplealarms careportal rawbg iob maker basal cob bwp cage delta direction upbat errorcodes","extendedSettings":{"cage":{"warn":"44","enablealerts":"true","urgent":"72","info":"40"}},"defaults": ...

![ns-f-cannulawarning](https://cloud.githubusercontent.com/assets/9641700/8728638/2e4569ca-2b9b-11e5-8a64-78f06ed00c5b.png)

**Comment by oamyoamy** [comment]
Popup upon hover: 

![ns-canulaage3](https://cloud.githubusercontent.com/assets/9641700/8728739/c3c87384-2b9b-11e5-9c8b-3bc538a5dba3.png)

**Comment by jasoncalabrese** [comment]
The way the notifications work now is that they are only sent in the 10 minute window to prevent duplicate alarms.  We were just discussing this on gitter :point_up: [July 16, 2015 10:18 AM](https://gitter.im/nightscout/public?at=55a7e7491a5d2fe320742160)

**Comment by StuArnold** [comment]
Left my little server running with my dev site on to ensure that I had the webpage open somewhere. Pushover was also running. No alarm messages received in Pushover for any of the 3 times and I did not see any alarms on my phone webview but I may have missed the 10 minute windows. Not having the Alarm is OK but a Pushover notification would be a good reminder to change the cannula.

**Comment by sulkaharo** [comment]
I'm debugging what's broken, apologies. 



—

**Comment by StuArnold** [comment]
I can see the time since Cannula changes but no alarms anywhere either in webapp or pushover at the appointed times. Cannot be sure I was viewing the webapp in the time window Jason mentioned but my microserver had the webapp open all weekend so expected it to at least trigger a Pushover message. I think we may have spoken in gitter last week and you were going to check whether it was reading the times correctly from Azure as they were in "" not showing as numbers - see first post above.

 "extendedSettings":{"cage":{"warn":"44","enablealerts":"true","urgent":"72","info":"40"}}

mine was similar to that. Does that help? Think this is excellent feature as we are always having to go into Careportal notes to check when we changed it.

**Comment by jasoncalabrese** [comment]
I think part of the solution here is storing the notifications/alarms and acks in mongo.   Then instead of the 10 minute window, we can check to see if there was already a notification.  Lots of other features will come from that too.  And other notifications like uploader battery would be possible.

**Comment by sulkaharo** [comment]
@StuArnold pushed a fix that should clear the core issue. Part of this is the documentation was wrong, and you actually need to set CAGE_ENABLE_ALARMS (note the underscore) to TRUE to enable the feature. This might be enough to fix this for you.

**Comment by StuArnold** [comment]
Thank you for working on this. Updated Dev and put a Cannula change 40 hours into the past. 44 Hour time just passed but no warning visible yet. Not sure if any of below is useful but at perhaps you may see an error I have made. Will update at 9pm tonight which is when the 48 hour warning is due. Do you think posting into past may be the issue in this case - I was just trying to avoid waiting for 44 hours but of course I could have set the times to 1, 2 & 3 hours just to test?

![image](https://cloud.githubusercontent.com/assets/10799221/8911171/baef3212-3482-11e5-8a18-db53389bd4d4.png)
![image](https://cloud.githubusercontent.com/assets/10799221/8911207/df93d992-3482-11e5-956f-196cfc5172de.png)
![image](https://cloud.githubusercontent.com/assets/10799221/8911223/f8a9c2d4-3482-11e5-9ae4-47c3e5c9560c.png)

**Comment by jasoncalabrese** [comment]
Really think the solution to this is storing the the notifications in mongo.  Right now all the logic to avoid dupes has to be handle by the plugin, need to offload that.

**Comment by sulkaharo** [comment]
#752 fixes the actual bug, introduced by a comparison change to make Codacy happy.

**Comment by sulkaharo** [comment]
This is now merged to dev. @StuArnold and @oamyoamy can you pull the latest dev, the feature should now work again.

**Comment by StuArnold** [comment]
Thanks @sulkaharo still not getting the Alerts though. Tried again yesterday in a period where there were no other Alarms (so not affected by silencing other alerts as mentioned by Jason in Gitter) with times set to 1 hour, 2 hour and 3 hours for the three levels. No alarms in webapp or pushover messages. Suspect that it may be because true in api is shown as "true" not true like the other occurrences in the status.json I am using CAGE_ENABLE_ALARMS as you suggested previously

**Comment by sulkaharo** [comment]
Ok let's see what's wrong. It's working for me now. Jason said snoozing alarms hides this as well, so can you confirm no alarms were snoozed before this? I'll commit a change to make cage use info level warns, which won't be snoozed. Other than that, can you post a screenshot of the cage settings, so I can double check the spelling just in case? :)

**Comment by StuArnold** [comment]
Can confirm nothing was snoozed in this time period.
![image](https://cloud.githubusercontent.com/assets/10799221/9108405/c8468e2e-3c25-11e5-9350-f944ec58aed3.png)
Will see if I can post pushover notifications from mobile in a minute
![image](https://cloud.githubusercontent.com/assets/10799221/9108440/fce25ee2-3c25-11e5-8c8e-fbf1e9119d33.png)
![image](https://cloud.githubusercontent.com/assets/10799221/9108458/1ab3ce38-3c26-11e5-9516-224e649298bb.png)
Jason said his true was not in "" in the status.json
![image](https://cloud.githubusercontent.com/assets/10799221/9108541/e08a8fca-3c26-11e5-8214-31f7deb1b64f.png)
but then his is different name. I will try moving back to CAGE_ENABLE_ALERTS and see if that helps.

**Comment by StuArnold** [comment]
Sorry posted status twice and not Azure
![image](https://cloud.githubusercontent.com/assets/10799221/9108592/3a243c8e-3c27-11e5-9e35-e0cce1a7e160.png)

**Comment by StuArnold** [comment]
From Pushover app showing no messages in hours before and after Site Change entered
![image](https://cloud.githubusercontent.com/assets/10799221/9109159/65ac61e8-3c2b-11e5-932c-e2ae53c59d06.png)

**Comment by StuArnold** [comment]
Changed back to CAGE_ENABLE_ALERTS and have now received the first pushover notification.

**Comment by StuArnold** [comment]
Next two alerts came through OK. So I am happy ;-) Thank you very much

**Comment by jasoncalabrese** [comment]
Think this is working good now, so I'm going to close the issue
