### ISSUE TITLE
Reports / Pulling wrong date for the data

### ISSUE THREAD

**Issue by oamyoamy** [nightscout/cgm-remote-monitor#993]
Report "dates" and "data" are not matching up. Daily Stats view.

For example, single day "today" option (9/12) is showing 9/12 data but the 9/11 as the date (the prior day). The readings here are from 9/12 but labeled as 9/11: 

![pulling-day-behind](https://cloud.githubusercontent.com/assets/9641700/9830659/f0d5406e-58eb-11e5-8a7a-e6105df9d85e.png)

Another example: a span of days, which includes the current date: The "dates" are all one day off of the data they are paired with:

![reports-dates-wrong](https://cloud.githubusercontent.com/assets/9641700/9830661/f6b5cb70-58eb-11e5-9eb0-f757a9fbefae.png)

(9/11 should be the one with 300 readings. The one with 5 readings is actually 9/12.)

**Comment by MilosKozak** [comment]
pm me link to your site pls

**Comment by MilosKozak** [comment]
should be solved in 0.8.1.
reopen if this issue if needed
@oamyoamy

**Comment by ks2coder** [comment]
The dates wrong is still an issue for me with the current version

**Comment by RPeterJ** [comment]
I have an issue with this on my 0.10.3 site. Is there a fix I can apply?

**Comment by sulkaharo** [comment]
@RPeterJ the related fixes are in the latest release; the fix is to upgrade to 0.12 series of Nightscout and then check the time zone in your treatment profile is correct
